import { Geist, Geist_Mono } from "next/font/google";
import { Caveat, M_PLUS_Rounded_1c } from "next/font/google";
import PaginationWrapper from "./components/paginationWrapper/PaginationWrapper";

import "./globals.css";
import NavBar from "./components/navbar/Navbar";

const caveat = Caveat({
  variable: "--font-caveat",
  subsets: ["latin"],
  weight: ["400", "700"], // adjust as per your design
});

const mPlus = M_PLUS_Rounded_1c({
  variable: "--font-mplus-rounded",
  subsets: ["latin"],
  weight: ["400", "700"], // you can include other weights as needed
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body className={`${caveat.variable} ${mPlus.variable} antialiased`}>
        <div className='min-h-screen flex flex-col'>
          <NavBar />
          <main className='flex-grow'>{children}</main>

          {/* <PaginationWrapper /> */}
        </div>
      </body>
    </html>
  );
}
